name: Deploy to EC2

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Login en Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Construir y subir imagen a Docker Hub
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/board-create-service .
        docker tag ${{ secrets.DOCKER_USERNAME }}/board-create-service:latest ${{ secrets.DOCKER_USERNAME }}/board-create-service:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/board-create-service:latest

    - name: Desplegar en EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/board-create-service:latest
          docker stop board-create-service || true
          docker rm board-create-service || true
          docker run -d --name board-create-service -p 4000:4000 --env-file .env ${{ secrets.DOCKER_USERNAME }}/board-create-service:latest
